# Generated by Django 5.1.1 on 2024-10-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_referenciassku'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferenciasSKU',
            new_name='Referencias',
        ),
    ]
