# Generated by Django 5.1.1 on 2024-10-07 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_menu_categoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='categoria_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.categoriamenu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
