# Generated by Django 5.1.1 on 2024-10-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_menu_categoria_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plu', models.CharField(max_length=100)),
                ('codsap', models.CharField(max_length=100)),
                ('marca_moto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'OINV',
            },
        ),
    ]
