# Generated by Django 5.1.1 on 2024-10-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_llantas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('', 'Civil'), ('2', 'Electrical'), ('3', 'Mechanical'), ('4', 'CompSci')], default='1', max_length=20)),
            ],
        ),
    ]
