# Generated by Django 5.1.1 on 2024-10-13 02:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_logger_email_logger_fecha_logger_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='fecha',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Ponga una fecha válida'),
        ),
    ]
