# Generated by Django 5.1.1 on 2024-10-13 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_logger_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='fecha',
        ),
    ]
